- type: web
  name: myapp-server
  runtime: node
  rootDir: server
  buildCommand: |
    # install only runtime deps (no dev needed since we’re not compiling here)
    npm ci --omit=dev
  startCommand: node dist/index.js
  envVars:
    - key: NODE_ENV
      value: production
- type: web
  name: myapp-client
  runtime: static
  rootDir: client
  buildCommand: |
    npm ci
    npm run build
  staticPublishPath: ./build
  routes:
    - type: rewrite
      source: "/*"
      destination: "/index.html"
