services:
  # Node API
  - type: web
    name: myapp-server
    runtime: node
    rootDir: server
    buildCommand: |
      npm install
      npm ci
      npm run build || echo "no server build step"
    startCommand: node index.ts # or: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # - key: DATABASE_URL
      #   sync: false
    healthCheckPath: /health

  # React client (static site)
  - type: web
    name: myapp-client
    runtime: static
    rootDir: client
    buildCommand: |
      npm install
      npm ci
      npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_BASE_URL
        value: https://myapp-server.onrender.com
