# render.yaml
services:
  - type: web
    name: myapp-server
    env: node
    rootDir: server
    buildCommand: |
      npm ci
      npm run build || echo "no build step"
    startCommand: |
      node server.js
      # or: npm start
    plan: starter
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # Add your secrets here or in dashboard:
      # - key: DATABASE_URL
      #   sync: false
    healthCheckPath: /health
    # If your server listens on process.env.PORT, no port config needed.

  - type: static
    name: myapp-client
    rootDir: client
    buildCommand: |
      npm ci
      npm run build
    publishPath: build
    # SPA rewrite so client-side routing works:
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      # For Vite: only variables prefixed with VITE_ are exposed to the client
      - key: VITE_API_BASE_URL
        value: https://myapp-server.onrender.com
