services:
  - type: web
    name: myapp-server
    runtime: node
    rootDir: server
    buildCommand: |
      # Install dev deps so TypeScript/@types are present
      npm ci --include=dev
      # Compile TS -> JS into dist/
      npm run build
    # Run the compiled JS (matches your package.json "start")
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: myapp-client
    runtime: static
    rootDir: client
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
